plugins {
	id 'java'
	id 'org.springframework.boot' version '3.3.2'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.ticket'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	// Spring Boot
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-webflux'

	// MyBatis
	implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:3.0.3'
	testImplementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter-test:3.0.3'

	// Lombok
	compileOnly 'org.projectlombok:lombok:1.18.40'
	annotationProcessor 'org.projectlombok:lombok:1.18.40'
	testCompileOnly 'org.projectlombok:lombok:1.18.40'
	testAnnotationProcessor 'org.projectlombok:lombok:1.18.40'

	// DevTools
	developmentOnly 'org.springframework.boot:spring-boot-devtools'

	// MySQL (추후 9.X로)
	runtimeOnly 'com.mysql:mysql-connector-j'

	// Tomcat + JSP + JSTL
	implementation 'org.apache.tomcat.embed:tomcat-embed-jasper:10.1.14' // jasper
	implementation 'jakarta.servlet.jsp.jstl:jakarta.servlet.jsp.jstl-api:2.0.0'
	runtimeOnly 'org.glassfish.web:jakarta.servlet.jsp.jstl:2.0.0'

	// P6Spy
	implementation 'com.github.gavlyukovskiy:p6spy-spring-boot-starter:1.9.0'

	// Jackson XML
	implementation 'com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.17.2'

	// Spring Boot Test
	testImplementation 'org.springframework.boot:spring-boot-starter-test'

	// JUnit 5 최신 안정화 (추후 6으로)
	testImplementation 'org.junit.jupiter:junit-jupiter:5.14.3'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	// Spring Boot Configuration Processor
	annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
}

tasks.named('test') {
	useJUnitPlatform()
}
